### PR TITLE
feature/ruby_snippets

### PR DESCRIPTION
**Pull request by florianjosefreheis**
Started adding support for ruby snippets. Feedback welcome.

### CODE REVIEW

**Comment by petrovicstefanrs** [comment]
Great man! Thank you very much for the contrib, I glanced over it and don't see any issues, as Ruby isn't really my language I'll have to trust you on code quality for the snippets. I assume I'll be able to merge this request by tomorrow. And by the start of the next week maybe even put out a new version of the snippet.

Once again thanks, and of course keep 'em coming! :D

**Comment by florianjosefreheis** [comment]
@petrovicstefanrs no worries, I try to add more snippets until the end of this week.

**Comment by petrovicstefanrs** [comment]
@florianjosefreheis Great! It would be awesome if we had at least 20, or more before we push Ruby out as well!

**Comment by petrovicstefanrs** [comment]
@florianjosefreheis hey man, thanks for keeping up with this. What do you think, about 5-10 more snippets and then merge?

**Comment by florianjosefreheis** [comment]
@petrovicstefanrs just pushed the rest of the snippets. We have now 20 ruby snippets. I will try to push another 5 this upcoming week.

**Comment by petrovicstefanrs** [comment]
@florianjosefreheis great man, I will merge it into dev now and prepare for the next release then. Thank you very much for this!

**Pull request merged**
