### PR TITLE
Feature/saved snippets

### PR DESCRIPTION
**Pull request by asantarissy**
This PR is created for a new added feature "Save Snippet", allowing users to save snippets for later.

### CODE REVIEW

**Comment by petrovicstefanrs** [comment]
Hey @asantarissy, 
Thanks for the feature and your time. I'm sorry that i delay the mere but I'm in the process of writing documentation for contributors and some rules as well.I want to leave this pr until then.

**Comment by petrovicstefanrs** [comment]
@asantarissy, I've finished reviewing the code. No objections here, other than leaving unused imports in components and a bit of inconsistent naming (Maybe its just me though). 

However, could you change this pr to be merged with dev branch instead of master. I want to use git flow, and merging directly into master would be troublesome.

Once I merge your PR into dev, I will probably do some naming changes, change icons to be from the same set as the others and do a bit of styling.

**Comment by asantarissy** [comment]
@petrovicstefanrs great, I changed the PR base to dev, and pulled the dev branch to it, let me clean it a little bit and push the edits again.

**Comment by asantarissy** [comment]
@petrovicstefanrs all is good, I pulled the dev branch and did some cleanups on my files.

Also, if I may, I added eslint and its plugins to devDependencies instead of using the global ones 😃 

Cheers!

**Comment by petrovicstefanrs** [comment]
> Also, if I may, I added eslint and its plugins to devDependencies instead of using the global ones 😃

I forgot to add them into devDependencies, didn't I ? Hhaha oooops. Mah bad! :D

**Comment by petrovicstefanrs** [comment]
@asantarissy Ok, merged, I hope to push my additions  over the weekend, and with your save feature push everything to staging by Monday. And possibly release everything finally as version 1.0.0.

I think there is enough features to call it a stable release... ☺️

**Pull request merged**
