### PR TITLE
Add C# Snippets

### PR DESCRIPTION
**Pull request by mrbeardy**
This adds all of the current snippets from [30 Seconds of C#](https://github.com/30-seconds/30-seconds-of-csharp), as well as the supporting code to have them show up in the extension.

### CODE REVIEW

**Comment by petrovicstefanrs** [comment]
@mrbeardy  I'll probably merge this over the weekend and maybe even release the new version at the same time.

**Comment by mrbeardy** [comment]
Cheers Stefan!

**Comment by petrovicstefanrs** [comment]
@mrbeardy I didn't notice you made a PR to `master`, and after changing to `develop` I noticed there is some code I can't remember what it was supposed to do. I'll take today to figure out what's up with `develop` branch and then I'll merge your branch into `develop`.

**Comment by mrbeardy** [comment]
Thanks @petrovicstefanrs.

If you'd like, I could just make the changes over in the `develop` branch and force push to the PR, or are there changes that need to happen in `develop` first to line it up with `master`?

**Comment by petrovicstefanrs** [comment]
> Thanks @petrovicstefanrs.
> 
> If you'd like, I could just make the changes over in the `develop` branch and force push to the PR, or are there changes that need to happen in `develop` first to line it up with `master`?

It's not your code that is the problem, it's my old code in `develop` that was left untouched for a long time. I'll need to sort that out first.

**Comment by petrovicstefanrs** [comment]
@mrbeardy Hey man, I've gone through the `dev branch`. Now that I know what's happening we can go through with the merge.

Would it be okay if you took your branch and `rebased` `dev` branch into it. After you're done with rebase just push again and I think we'll be able to merge without any conflicts.

**Comment by mrbeardy** [comment]
Hey @petrovicstefanrs, I rebased `dev` but this branch still had commits from master and shown a bunch of extra commits in the PR, so I've deleted the branch and created a new one from `dev` with the changes from the old branch, so we should be all clear to merge this into `dev` cleanly now 😃. 

Lemme know if there's anything else that needs to be done on this branch.

**Comment by petrovicstefanrs** [comment]
> Hey @petrovicstefanrs, I rebased `dev` but this branch still had commits from master and shown a bunch of extra commits in the PR, so I've deleted the branch and created a new one from `dev` with the changes from the old branch, so we should be all clear to merge this into `dev` cleanly now 😃.
> 
> Lemme know if there's anything else that needs to be done on this branch.

Well that's one way to do it :D

Anyway, looks good to me now. Merging!

**Comment by petrovicstefanrs** [comment]
@mrbeardy Next thing, I'll have to merge the work other people did while I was not able to work on this, and prepare a new version! :D

**Pull request merged**
