### PR TITLE
added C++ support

### PR DESCRIPTION
**Pull request by Bhupesh-V**
## Added C++ snippets from [30 Seconds of C++](https://github.com/Bhupesh-V/30-seconds-of-cpp)

### CODE REVIEW

**Comment by petrovicstefanrs** [comment]
I'll need to add an option to support c++ first. Then we can merge this, however the folder for c++ can't be named "c++" it should be "cpp". Also if there is a repo where you have all these snippets could you link to it here so others can help with migrating the snippets.

**Comment by Bhupesh-V** [comment]
Ok I have changed the directory name to ```cpp```
I will be add C++ snippets to this [directory](https://github.com/Bhupesh-V/30-seconds-of-cpp/tree/master/snippets).
Also ping me when you will be adding  support for C++ , I will provide you with the logo :smiley:

**Comment by petrovicstefanrs** [comment]
@Bhupesh-V Hey man, I've started merging all PRs and I'm just about to merge C++ snippets, I don't however want to release them before we have at least 20-30 snippets. So the question is, do you have more snippets or is this all? 😄

**Comment by Bhupesh-V** [comment]
> @Bhupesh-V Hey man, I've started merging all PRs and I'm just about to merge C++ snippets, I don't however want to release them before we have at least 20-30 snippets. So the question is, do you have more snippets or is this all?

Hey :smile: sure , I have added more snippets(26 in total) also do I have to push a template for C++ Snippets in the `templates/` directory ?
I will also ping you once the Logo is ready

**Comment by petrovicstefanrs** [comment]
@Bhupesh-V Hey, it would be great if you could also push the template, as for the logo there is no need for it. If you are taking the snippets from a separate repo do send me a link so I can backlink to the original repo in readme and on other places :D

**Comment by petrovicstefanrs** [comment]
@Bhupesh-V Also I see you are using ** notation to mark sections in the template, you should check other templates, you'll se they use #### for section names and ### for snippet title. We should keep these the same across the templates.

**Pull request merged**
