### PR TITLE
spelling correction: Mehtod -> Method

### PR DESCRIPTION
**Pull request by keif**
Spelling correction for a Ruby snippet.

### CODE REVIEW

**Comment by florianjosefreheis** [comment]
@petrovicstefanrs, this can be merged if you have a second! Cheers.

**Comment by petrovicstefanrs** [comment]
@keif do this but on the dev branch as a base, I'm not merging into master. Please read the readme.md I've said this to 99% of the PRs

**Comment by keif** [comment]
Cool.

You mean this link? https://github.com/petrovicstefanrs/30_seconds_of_knowledge/wiki/Ruby-Snippets

Or this one? https://github.com/petrovicstefanrs/30_seconds_of_knowledge/wiki

None of them say "use the dev branch" and I didn't read "99% of the PRs" so if perhaps that's worth adding somewhere up front in the wiki and not hidden in a subpage.

**Comment by florianjosefreheis** [comment]
good catch @petrovicstefanrs.
@keif it's the first link, more specific:
https://github.com/petrovicstefanrs/30_seconds_of_knowledge/wiki#codebase-contributing

Would be great if you could follow the [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

**Comment by petrovicstefanrs** [comment]
@keif Just like @florianjosefreheis said. However it seams I will need to emphasize that part of the wiki more as no one seams to catch on it.

**Pull request closed without merging**
